apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: spyre
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - spyre
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/spyre: ''
