ui:
  # @hidden
  image: icr.io/ai-services-cicd/rag-ui:v0.0.18

backend:
  # @hidden
  image: icr.io/ai-services-cicd/rag:v0.0.27
  # @hidden
  log_level: "INFO"

instruct:
  # @hidden
  image: registry.redhat.io/rhaiis/vllm-spyre-rhel9:3.2.5
  # @hidden
  storageUri: hf://ibm-granite/granite-3.3-8b-instruct

embedding:
  # @hidden
  image: icr.io/ppc64le-oss/vllm-ppc64le:0.9.1
  # @hidden
  storageUri: hf://ibm-granite/granite-embedding-278m-multilingual

reranker:
  # @hidden
  image: icr.io/ppc64le-oss/vllm-ppc64le:0.9.1
  # @hidden
  storageUri: hf://BAAI/bge-reranker-v2-m3


ingest:
  # @hidden
  log_level: "INFO"

opensearch:
  # @hidden
  image: icr.io/ppc64le-oss/opensearch-ppc64le:3.3.0
  # @description Sets the memory limit for the Opensearch service(Default: 4Gi). Override by passing a value with a unit suffix (e.g., Mi, Gi).
  memoryLimit: 4Gi
  # @description Sets the storage limit for the Opensearch service(Default: 10Gi). Override by passing a value with a unit suffix (e.g., Mi, Gi).
  storage: 10Gi
  auth:
    username: "admin"
    password: "AiServices@1234"
