name: Spyre RAG UI
on:
  push:
    paths:
      - 'spyre-rag/ui/**'
    branches:
      - main
  pull_request:
    paths:
      - 'spyre-rag/ui/**'
    branches:
      - main

env:
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: spyre-rag/ui/package-lock.json

      - name: Install dependencies
        working-directory: spyre-rag/ui
        run: npm ci

      - name: Run linter
        working-directory: spyre-rag/ui
        run: npm run lint

  build-publish-image:
    name: Build and Publish Image
    needs: lint
    runs-on: ubuntu-24.04-ppc64le

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build spyre-rag-ui image
        working-directory: spyre-rag/ui
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}

      - name: Publish spyre-rag-ui image
        working-directory: spyre-rag/ui
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          make push REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} REGISTRY_USER=${{ secrets.ICR_USERNAME }} REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}
